'use strict'
chrome.runtime.onInstalled.addListener (details) ->
  console.log 'previousVersion', details.previousVersion
  return
chrome.browserAction.setBadgeText text: '\'Allo'
console.log '\'Allo \'Allo! Event Page for Browser Action'

# ---
# generated by js2coffee 2.0.3
