name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
          cache: pnpm
      - run: pnpm build
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: devdocs_web_ext-${{ steps.get_version.outputs.version-without-v }}.zip
